proyecto-entreno/Comercial/urls.py
from django.urls import path, include
from . import views

urls_cuotas = [
    path('<pk>/update', views.CuotaUpdate.as_view(), name='update'),
    path('impagas', views.CuotasImpagas.as_view(), name='impagas')
]

urls_legajo = [
    path('list', views.LegajosTodosList.as_view(), name='list'),
    path('<pk>/update', views.LegajoUpdate.as_view(), name='update'),
    path('<pk>/detail', views.LegajoComercialDetail.as_view(), name='detail')
]

urlpatterns = [
    path('cuotas/', include((urls_cuotas, 'Comercial'), namespace='cuotas')),
    path('legajos/', include((urls_legajo, 'Comercial'), namespace='legajos'))
]

proyecto-entreno/PE/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import TemplateView

from PE.views import Home

urlpatterns = [
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('admin/', admin.site.urls),
                  path('entreno/', include(('Entreno.urls', 'Entreno'))),
                  path('comercial/', include(('Comercial.urls', 'Comercial'))),
                  path('salud/', include(('Salud.urls', 'Salud'))),
                  path('', Home.as_view(), name='home')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto-entreno/Comercial/models.py
import logging

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.timezone import now

from Entreno.models import Atleta


class LegajoComercial(models.Model):
    TALLES_CHOICES = ((1, 'XXS'),
                      (2, 'XS'),
                      (3, 'S'),
                      (4, 'M'),
                      (5, 'L'),
                      (6, 'XL'),
                      (7, 'XXL'))

    atleta = models.OneToOneField(Atleta, on_delete=models.CASCADE)
    fecha_inscripcion = models.DateField(default=now)
    activo = models.BooleanField(default=True)
    becado = models.BooleanField(default=False)

    talle = models.IntegerField(choices=TALLES_CHOICES, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('Comercial:legajos:detail', kwargs={'pk': self.id})

    @property
    def con_deuda(self):
        return self.activo and not self.becado and self.cuota_set.filter(fecha_pago__isnull=True).exists()

    class Meta:
        ordering = ["atleta__apellido", "atleta__nombre"]
        verbose_name = "Legajo Comercial"
        verbose_name_plural = "Legajos Comerciales"

    def __str__(self):
        return 'Leg. ' + self.atleta.apellido + ', ' + self.atleta.nombre


def anio_actual():
    return now().year


class Periodo(models.Model):
    MESES_CHOICES = ((1, "Enero"),
                     (2, "Febrero"),
                     (3, "Marzo"),
                     (4, "Abril"),
                     (5, "Mayo"),
                     (6, "Junio"),
                     (7, "Julio"),
                     (8, "Agosto"),
                     (9, "Septiembre"),
                     (10, "Octubre"),
                     (11, "Noviembre"),
                     (12, "Diciembre"))
    fecha = models.DateField(default=now)
    mes = models.IntegerField(choices=MESES_CHOICES)
    anio = models.IntegerField(default=anio_actual)
    debitado = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Periodo"
        verbose_name_plural = "Periodos"
        unique_together = ('anio', 'mes')

    def __str__(self):
        return str(self.get_mes_display()) + '/' + str(self.anio)


class Cuota(models.Model):
    fecha = models.DateField(default=now)
    legajo = models.ForeignKey(LegajoComercial, on_delete=models.CASCADE)
    periodo = models.ForeignKey(Periodo, on_delete=models.CASCADE)
    fecha_pago = models.DateField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse('Comercial:cuotas:update', kwargs={'pk': self.id})

    class Meta:
        verbose_name = "Cuota"
        verbose_name_plural = "Cuotas"

    def __str__(self):
        return str(self.id) + ' ' + str(self.periodo)


@receiver(post_save, sender=Cuota)
def __pasar_inactivo_legajo_post_cuota_save(sender, **kwargs):
    try:
        cuota = kwargs.get('instance')
        legajo = cuota.legajo
        conteo = Cuota.objects.filter(legajo=legajo, fecha_pago__isnull=True).count()
        legajo.activo = 2 > conteo
        legajo.save()

    except Exception as e:
        raise e


@receiver(post_save, sender=Periodo)
def __debitar_cuotas_por_periodo_post_save(sender, **kwargs):
    periodo = kwargs.get('instance')  # type: Periodo
    if not periodo.debitado:
        legajos = LegajoComercial.objects.exclude(activo=False, becado=True)
        for legajo in legajos:
            Cuota(legajo=legajo, periodo=periodo).save()
        periodo.debitado = True
        periodo.save()


@receiver(post_save, sender=Atleta)
def __crear_legajo_comercial_on_atleta_post_save(sender, **kwargs):
    try:
        atleta = kwargs.get('instance')  # type: Atleta
        legajo, created = LegajoComercial.objects.get_or_create(atleta=atleta)
        logging.info(f'Legajo comercial: {legajo} Creado: {created}')
    except Exception as e:
        logging.exception(e)
        raise e

proyecto-entreno/Comercial/forms.py
from django import forms
from django.forms import ModelForm

from Comercial.models import Cuota
from PE.validators import no_future_date_validator


class CuotaUpdateForm(ModelForm):
    fecha_pago = forms.DateField(validators=[no_future_date_validator])
    class Meta:
        model = Cuota
        fields = ['fecha_pago']

proyecto-entreno/Comercial/views.py
import logging
import threading
from datetime import datetime, timedelta

from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView

from Comercial.forms import CuotaUpdateForm
from .models import LegajoComercial, Cuota, Periodo

FECHA_TESTIGO = datetime.now()  # type: datetime


def debitar_periodo(ahora):
    ultimo_periodo = Periodo.objects.order_by('-id')[0]
    if ultimo_periodo.anio < ahora.year or ultimo_periodo.mes < ahora.month:
        nuevo_periodo = Periodo(mes=ahora.month, anio=ahora.year, fecha=ahora)
        nuevo_periodo.save()
        return nuevo_periodo


def check_thread(thread_event, logger):
    global FECHA_TESTIGO
    ahora = datetime.now()
    if FECHA_TESTIGO.year < ahora.year or FECHA_TESTIGO.month < ahora.month:
        periodo = debitar_periodo(ahora)
        FECHA_TESTIGO = ahora
        logger.info(f'Debitado el periodo: {periodo}')
    if not thread_event.is_set():
        maniana = ahora + timedelta(days=1)
        sleep_time = maniana - ahora
        thread = threading.Timer(sleep_time.total_seconds(), check_thread, [thread_event, logger])
        thread.start()


def start_monitor():
    logger = logging.getLogger(__name__)
    logger.setLevel('DEBUG')
    event = threading.Event()
    logger.info("Iniciando thread de debito de periodos")
    check_thread(event, logger)


class CuotaDetail(DetailView):
    template_name = 'cuota_detail.html'
    model = Cuota


class CuotaUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'cuota_form.html'
    model = Cuota
    form_class = CuotaUpdateForm

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(CuotaUpdate, self).get_context_data(**kwargs)
        # Add in context data
        cuota = context['object']
        context['titulo'] = "Actualizando una cuota"
        context['subtitle'] = f'{cuota.periodo}. {cuota.legajo.atleta}'
        return context


class CuotasImpagas(LoginRequiredMixin, ListView):
    template_name = 'cuota_list.html'
    model = Cuota
    queryset = Cuota.objects.filter(fecha_pago__isnull=True).all()
    success_url = reverse_lazy('Comercial:cuotas:impagas')


class CuotasDelLegajo(LoginRequiredMixin, TemplateView):
    template_name = 'CuotasDelLegajo.html'

    class CuotasDelLegajoForm(forms.Form):
        legajo = forms.ModelChoiceField(queryset=LegajoComercial.objects.all())

    def get_context_data(self, **kwargs):
        context = super(CuotasDelLegajo, self).get_context_data(**kwargs)
        context['form_cuotas'] = self.CuotasDelLegajoForm()

        if 'legajo' in self.request.GET:
            leg = LegajoComercial.objects.get(id=self.request.GET['legajo'])
            context['legajo'] = leg
            context['object_list'] = Cuota.objects.filter(legajo=leg)

        return context


class LegajoUpdate(LoginRequiredMixin, UpdateView):
    model = LegajoComercial
    fields = ['fecha_inscripcion', 'activo', 'becado', 'talle']
    template_name = 'legajo_form.html'
    success_url = reverse_lazy('Comercial:legajos:list')

    def get_context_data(self, **kwargs):
        context = super(LegajoUpdate, self).get_context_data(**kwargs)
        legajo = context['object']  # type: LegajoComercial
        context['titulo'] = f"Legajo comercial: {legajo.atleta}"
        return context


class LegajoComercialDetail(DetailView):
    model = LegajoComercial
    template_name = 'legajocomercial_detail.html'

    def get_context_data(self, **kwargs):
        context = super(LegajoComercialDetail, self).get_context_data(**kwargs)
        context['titulo'] = f"Legajo comercial"
        return context


class LegajosTodosList(ListView):
    template_name = 'legajo_list.html'
    queryset = LegajoComercial.objects.all()

proyecto-entreno/Comercial/templates/cuota_form.html
{% extends 'dashboard.html' %}
{% load static %}


{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
{% endblock %}


{% block content %}
    <div class="box box-block bg-white">
        <h2 class="h-underline h-underline-100 h-underline-primary">{{ titulo }}
            <small class="text-muted"><a href="{% url 'Comercial:legajos:detail' object.legajo.id %}"> ver </a></small>
        </h2>
        <div class="row">
            <div class="col-sm-12 col-md-3">
                {% with atleta=object.legajo.atleta %}
                    {% include 'perfil_atleta.html' %}
                {% endwith %}
            </div>
            <div class="col-sm-12 col-md-5">
                <h5>{{ subtitle }}</h5>
                {% include 'form_generico.html' %}
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/bootstrap-datepicker/js/locales/bootstrap-datepicker.es.js' %}"></script>
    <script type="application/javascript">
        $('#id_fecha_pago').datepicker({
            language: 'es',
            autoclose: true,
		    todayHighlight: true
        });
    </script>
{% endblock %}

proyecto-entreno/Comercial/templates/cuota_list.html
{% extends 'datatable_shell.html' %}
{% block table_title %}
    Cuotas impagas
{% endblock %}

{% block thead %}
    <tr>
        <th>N°</th>
        <th>Legajo</th>
        <th>Período</th>
        <th>Fecha de débito</th>
        <th>Fecha de pago</th>
    </tr>

{% endblock %}

{% block tbody %}
    {% for c in object_list %}
        <tr>
            <td>
            <a href="{% url 'Comercial:cuotas:update' c.id %}">{{ c.id }}</a>
            </td>
            <td>
                {{ c.legajo.atleta }}
            </td>
            <td class="error">{{ c.periodo }}</td>
            <td>{{ c.fecha }}</td>
            <td>{{ c.fecha_pago | default_if_none:'n/d' }}</td>
        </tr>
    {% endfor %}
{% endblock %}

{% block tfoot %}
    <tr>
        <th>N°</th>
        <th>Legajo</th>
        <th>Período</th>
        <th>Fecha de débito</th>
        <th>Fecha de pago</th>
    </tr>
{% endblock %}

proyecto-entreno/Comercial/templates/cuota_table.html
{% extends 'datatable_shell.html' %}

{% block thead %}
    <tr>
        <th>N°</th>
        <th>Legajo</th>
        <th>Período</th>
        <th>Fecha de débito</th>
        <th>Fecha de pago</th>
    </tr>

{% endblock %}

{% block tbody %}
    {% for c in object_list %}
        <tr>
            <td>
            <a href="{% url 'Comercial:cuotas:update' c.id %}">{{ c.id }}</a>
            </td>
            <td>
                {{ c.legajo.atleta }}
            </td>
            <td class="error">{{ c.periodo }}</td>
            <td>{{ c.fecha }}</td>
            <td>{{ c.fecha_pago | default_if_none:'n/d' }}</td>
        </tr>
    {% endfor %}
{% endblock %}

{% block tfoot %}
    <tr>
        <th>N°</th>
        <th>Legajo</th>
        <th>Período</th>
        <th>Fecha de débito</th>
        <th>Fecha de pago</th>
    </tr>
{% endblock %}

proyecto-entreno/Comercial/templates/legajo_form.html
{% extends 'dashboard.html' %}
{% load static %}


{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
{% endblock %}


{% block content %}
    <div class="box box-block bg-white">
        <h2 class="h-underline h-underline-100 h-underline-primary">{{ titulo }}
            <small class="text-muted"><a href="{% url 'Comercial:legajos:detail' object.id %}"> ver </a></small>
        </h2>
        <div class="row">
            <div class="col-sm-12 col-md-3">
                {% with atleta=object.atleta %}
                    {% include 'perfil_atleta.html' %}
                {% endwith %}
            </div>
            <div class="col-sm-12 col-md-5">
                {% include 'form_generico.html' %}
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/bootstrap-datepicker/js/locales/bootstrap-datepicker.es.js' %}"></script>
    <script type="application/javascript">
        $('#id_fecha_inscripcion').datepicker({
            language: 'es',
            autoclose: true,
		    todayHighlight: true
        });
    </script>
{% endblock %}

proyecto-entreno/Comercial/templates/legajo_list.html
{% extends 'datatable_shell.html' %}

{% block table_title %}
Legajos comerciales
{% endblock %}

{% block thead %}
    <tr>
        <th>N° leg</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>F. Inscripción</th>
        <th>Activo</th>
        <th>Becado</th>
        <th>Con deuda</th>
        <th>Talle remera</th>
    </tr>
{% endblock %}

{% block tbody %}
    {% for legajo in object_list %}
        <tr>
            <td><a href="{{ legajo.get_absolute_url }}" class="btn btn-outline-primary">{{ legajo.id }}</a></td>
            <td>{{ legajo.atleta.nombre }}</td>
            <td>{{ legajo.atleta.apellido }}</td>
            <td>{{ legajo.fecha_inscripcion }}</td>
            <td>{{ legajo.activo | yesno }}</td>
            <td>{{ legajo.becado | yesno }}</td>
            <td>{{ legajo.con_deuda | yesno }}</td>
            <td>{{ legajo.get_talle_display | default_if_none:'n/d' }}</td>
        </tr>
    {% endfor %}
{% endblock %}

{% block tfoot %}
    <tr>
        <th>N° leg</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>F. Inscripción</th>
        <th>Activo</th>
        <th>Becado</th>
        <th>Con deuda</th>
        <th>Talle remera</th>
    </tr>
{% endblock %}

proyecto-entreno/Comercial/templates/legajocomercial_detail.html
{% extends 'datatable_shell.html' %}
{% load static %}

{% block content %}
    <div class="box box-block bg-white">
        <h2 class="h-underline h-underline-100 h-underline-primary">{{ titulo }}
            <small class="text-muted"><a href="{% url 'Comercial:legajos:update' object.id %}"> editar </a></small>
        </h2>
        {% if subtitle %}
            <h6>{{ subtitle }}</h6>
        {% endif %}
        <div class="row">
            <div class="col-sm-12 col-md-3">
                {% with atleta=object.atleta %}
                    {% include 'perfil_atleta.html' %}
                {% endwith %}
            </div>
            <div class="col-sm-12 col-md-4">
                <div class="box box-block bg-white">
                    <h5>Detalles:</h5>

                    <div class="clearfix m-b-0-25">
                        <span class="pull-xs-left"><strong>Con deuda:</strong></span>
                        <span class="pull-xs-right">{{ object.con_deuda | yesno | upper }}</span>
                    </div>
                    <div class="clearfix m-b-0-25">
                        <span class="pull-xs-left"><strong>Activo:</strong></span>
                        <span class="pull-xs-right">{{ object.activo | yesno | upper }}</span>
                    </div>
                    <div class="clearfix m-b-0-25">
                        <span class="pull-xs-left"><strong>Becado:</strong></span>
                        <span class="pull-xs-right">{{ object.becado | yesno | upper }}</span>
                    </div>
                    <div class="clearfix m-b-0-25">
                        <span class="pull-xs-left"><strong>Fecha de inscripción:</strong></span>
                        <span class="pull-xs-right">{{ object.fecha_inscripcion }}</span>
                    </div>
                    <div class="clearfix m-b-0-25">
                        <span class="pull-xs-left"><strong>Talle:</strong></span>
                        <span class="pull-xs-right">{{ object.get_talle_display }}</span>
                    </div>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-sm-12">
                {{ block.super }} <!--Call to fucking table-->
            </div>
        </div>
    </div>
{% endblock %}

{% block table_title %}Cuotas{% endblock %}


{% block thead %}
    <tr>
        <th>N°</th>
        <th>Legajo</th>
        <th>Período</th>
        <th>Fecha de débito</th>
        <th>Fecha de pago</th>
    </tr>

{% endblock %}

{% block tbody %}
    {% for cuota in object.cuota_set.all %}
        <tr>
            <td><a href="{% url 'Comercial:cuotas:update' cuota.id %}" class="btn btn-outline-primary">{{ cuota.id }}</a></td>
            <td>
                {{ cuota.legajo.atleta }}
            </td>
            <td class="error">{{ cuota.periodo }}</td>
            <td>{{ cuota.fecha }}</td>
            <td>{{ cuota.fecha_pago | default_if_none:'IMPAGA' }}</td>
        </tr>
    {% endfor %}
{% endblock %}

{% block tfoot %}
    <tr>
        <th>N°</th>
        <th>Legajo</th>
        <th>Período</th>
        <th>Fecha de débito</th>
        <th>Fecha de pago</th>
    </tr>
{% endblock %}