proyecto-entreno/Entreno/urls.py
from django.urls import path, include
from . import views

urls_atletas = [
    path('add', views.AtletaCreate.as_view(), name='add'),
    path('<pk>/update', views.AtletaUpdate.as_view(), name='update'),
    path('list', views.AtletasList.as_view(), name='list'),
    path('<pk>/detail', views.AtletaDetail.as_view(), name='detail')
]

urlpatterns = [
    path('atletas/', include((urls_atletas, 'Entreno'), namespace='atletas'))
]

proyecto-entreno/PE/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import TemplateView

from PE.views import Home

urlpatterns = [
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('admin/', admin.site.urls),
                  path('entreno/', include(('Entreno.urls', 'Entreno'))),
                  path('comercial/', include(('Comercial.urls', 'Comercial'))),
                  path('salud/', include(('Salud.urls', 'Salud'))),
                  path('', Home.as_view(), name='home')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto-entreno/Entreno/models.py
from django.db import models
from django.urls import reverse


class Atleta(models.Model):
    dni = models.IntegerField(unique=True)
    nombre = models.CharField(max_length=140)
    apellido = models.CharField(max_length=140)
    fecha_nacimiento = models.DateField()
    domicilio = models.CharField(max_length=140)
    telefono_personal = models.CharField(max_length=40)
    telefono_referencia = models.CharField(max_length=40, null=True, blank=True)
    email = models.EmailField(max_length=240, null=True, blank=True)
    fecha_inicio_actividad = models.DateField(null=True, blank=True)
    observaciones = models.CharField(max_length=500, null=True, blank=True)
    foto = models.ImageField(upload_to='fotos_atletas/', null=True, blank=True)

    def __str__(self):
        return self.apellido + ', ' + self.nombre


    def get_absolute_url(self):
        return reverse('Entreno:atletas:detail', kwargs={'pk': self.id})

    class Meta:
        ordering = ["apellido", "nombre"]
        verbose_name = "Atleta"
        verbose_name_plural = "Atletas"


class Marca(models.Model):
    PRUEBA_CHOICES = (
        # pista
        (1, '60m'),
        (2, '100m llanos'),
        (3, '100m con vallas'),
        (4, '110m con vallas'),
        (5, '150m llanos'),
        (6, '200m llanos'),
        (7, '300m llanos'),
        (8, '400m llanos'),
        (9, '400m con vallas'),
        (10, '500m llanos'),
        (11, '600m llanos'),
        (12, '800m'),
        (14, '1000m'),
        (15, '1200m'),
        (16, '1500m'),
        (17, '3000m llanos'),
        (18, '3000m con obstáculos'),
        (19, '5000m'),
        (31, '10000m'),
        # de calle
        (120, '3000m calle'),
        (121, '5000m calle'),
        (122, '7000m calle'),
        (125, '10000m calle'),
        (127, '21095m calle'),
        (128, '42196m calle'),
        (129, '20000m marcha calle'),
        (130, '50000m marcha calle'),
        # cross
        (222, '5000m cross'),
        (223, '7000m cross'),
        (226, '10000m cross'),
        (227, '21095m cross'),
        (228, '42196m cross')
    )

    atleta = models.ForeignKey(Atleta, on_delete=models.CASCADE)
    fecha = models.DateField()
    descripcion = models.CharField(max_length=500, null=True, blank=True)
    prueba = models.IntegerField(choices=PRUEBA_CHOICES)
    marca = models.DurationField()

    class Meta:
        verbose_name = "Marca"
        verbose_name_plural = "Marcas"

proyecto-entreno/Entreno/forms.py
from django import forms
from django.forms import ModelForm

from Entreno.models import Atleta
from PE.validators import no_future_date_validator


class AtletaForm(ModelForm):
    fecha_nacimiento = forms.DateField(validators=[no_future_date_validator], required=True)
    fecha_inicio_actividad = forms.DateField(validators=[no_future_date_validator], required=True)

    class Meta:
        model = Atleta
        fields = ['dni', 'nombre', 'apellido', 'fecha_nacimiento', 'domicilio', 'telefono_personal',
                  'telefono_referencia', 'email', 'fecha_inicio_actividad', 'observaciones', 'foto']

proyecto-entreno/Entreno/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, UpdateView, ListView

from Entreno.forms import AtletaForm
from Entreno.models import Atleta
from . import models


class AtletaDetail(LoginRequiredMixin, DetailView):
    template_name = 'atleta_detail.html'
    model = models.Atleta

    def get_context_data(self, **kwargs):
        context = super(AtletaDetail, self).get_context_data(**kwargs)
        atleta = context['object']  # type: models.Atleta
        context['titulo'] = f"{atleta}"
        return context


class AtletaCreate(LoginRequiredMixin, CreateView):
    template_name = 'atleta_form.html'
    model = models.Atleta
    form_class = AtletaForm

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(AtletaCreate, self).get_context_data(**kwargs)
        # Add in context data
        context['titulo'] = "Cargando un atleta"
        return context


class AtletaUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'atleta_form.html'
    model = models.Atleta
    form_class = AtletaForm

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(AtletaUpdate, self).get_context_data(**kwargs)
        # Add in context data
        context['titulo'] = "Actualizando un atleta"
        return context

class AtletasList(LoginRequiredMixin, ListView):
    model = models.Atleta
    queryset = Atleta.objects.all()
    template_name = 'atleta_list.html'

proyecto-entreno/Entreno/templates/atleta_detail.html
{% extends 'dashboard.html' %}
{% load static %}

{% block content %}
    <div class="box box-block bg-white">
        <h2 class="h-underline h-underline-100 h-underline-primary">{{ titulo }}
            <small class="text-muted"><a href="{% url 'Entreno:atletas:update' object.id %}"> editar </a></small>
        </h2>
        {% if subtitle %}
            <h6>{{ subtitle }}</h6>
        {% endif %}
        <div class="row">
            <div class="col-sm-12 col-md-3">
                {% with atleta=object %}
                    {% include 'perfil_atleta.html' %}
                {% endwith %}
            </div>
            <div class="col-sm-12 col-md-4">
                <div class="box box-block bg-white">
                    <h5>Detalles:</h5>
                    <div class="clearfix m-b-0-25">
                        <span class="pull-xs-left"><strong>DNI:</strong></span>
                        <span class="pull-xs-right">{{ object.dni }}</span>
                    </div>
                    <div class="clearfix m-b-0-25">
                        <span class="pull-xs-left"><strong>Fecha de nacimiento:</strong></span>
                        <span class="pull-xs-right">{{ object.fecha_nacimiento }}</span>
                    </div>
                    <div class="clearfix m-b-0-25">
                        <span class="pull-xs-left"><strong>Teléfono de referencia:</strong></span>
                        <span class="pull-xs-right">{{ object.telefono_referencia }}</span>
                    </div>
                    <div class="clearfix m-b-0-25">
                        <span class="pull-xs-left"><strong>Fecha de inicio de actividad:</strong></span>
                        <span class="pull-xs-right">{{ object.fecha_inicio_actividad }}</span>
                    </div>
                    <div class="clearfix m-b-0-25">
                        <span class="pull-xs-left"><strong>Observaciones:</strong></span>
                        <span class="pull-xs-right">{{ object.observaciones }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

proyecto-entreno/Entreno/templates/atleta_form.html
{% extends 'dashboard.html' %}
{% load static %}


{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
{% endblock %}


{% block content %}
    <div class="box box-block bg-white">
        <h2 class="h-underline h-underline-100 h-underline-primary">{{ titulo }}
            {% if object %}
            <small class="text-muted"><a href="{% url 'Entreno:atletas:detail' object.id %}"> ver </a></small>
            {% endif %}
        </h2>
        <div class="row">
            <div class="col-sm-12 col-md-3">
                {% with atleta=object %}
                    {% include 'perfil_atleta.html' %}
                {% endwith %}
            </div>
            <div class="col-sm-12 col-md-5">
                {% include 'form_generico.html' %}
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/bootstrap-datepicker/js/locales/bootstrap-datepicker.es.js' %}"></script>
    <script type="application/javascript">
        $('#id_fecha_nacimiento, #id_fecha_inicio_actividad').datepicker({
            language: 'es',
            autoclose: true,
		    todayHighlight: true
        });
    </script>
{% endblock %}

proyecto-entreno/Entreno/templates/atleta_list.html
{% extends 'datatable_shell.html' %}

{% block table_title %}
    Todos los atletas
{% endblock %}

{% block thead %}
    <tr>
        <th>N° leg</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>DNI</th>
        <th>F. Nac.</th>
        <th>Domicilio</th>
        <th>T. Personal</th>
        <th>T. Referencia</th>
        <th>E-Mail</th>
    </tr>

{% endblock %}

{% block tbody %}
    {% for atleta in object_list %}
        <tr>
            <td><a href="{{ atleta.get_absolute_url }}" class="btn btn-outline-primary">{{ atleta.id }}</a></td>
            <td>{{ atleta.nombre }}</td>
            <td>{{ atleta.apellido }}</td>
            <td>{{ atleta.dni }}</td>
            <td>{{ atleta.fecha_nacimiento }}</td>
            <td>{{ atleta.domicilio }}</td>
            <td>{{ atleta.telefono_personal }}</td>
            <td>{{ atleta.telefono_referencia }}</td>
            <td>{{ atleta.email }}</td>
        </tr>
    {% endfor %}
{% endblock %}

{% block tfoot %}
    <tr>
        <th>N° leg</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>F. Nac.</th>
        <th>Domicilio</th>
        <th>T. Personal</th>
        <th>T. Referencia</th>
        <th>E-Mail</th>
    </tr>
{% endblock %}

proyecto-entreno/Entreno/templates/perfil_atleta.html
{% load static %}
<div class="card profile-card">
    <div class="profile-avatar">
        {% if atleta.foto %}
            <img src="{{ atleta.foto.url }}" alt="">
        {% else %}
            <img src="{% static 'img/user.svg' %}" alt="">
        {% endif %}
    </div>
    <div class="card-block">
        <h4 class="m-b-0-25">{{ atleta.nombre }} {{ atleta.apellido }}</h4>

    </div>
    <ul class="list-group">
        {% if atleta.telefono_personal %}
            <a class="list-group-item" href="tel:+{{ atleta.telefono_personal }}">
                <i class="ti-mobile m-r-0-5"></i>{{ atleta.telefono_personal }}
            </a>
        {% endif %}

        {% if  atleta.email %}
            <a class="list-group-item" href="mailto:{{ atleta.email }}">
                <i class="ti-email m-r-0-5"></i>{{ atleta.email }}
            </a>
        {% endif %}
    </ul>
</div>