proyecto-entreno/PE/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import TemplateView

from PE.views import Home

urlpatterns = [
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('admin/', admin.site.urls),
                  path('entreno/', include(('Entreno.urls', 'Entreno'))),
                  path('comercial/', include(('Comercial.urls', 'Comercial'))),
                  path('salud/', include(('Salud.urls', 'Salud'))),
                  path('', Home.as_view(), name='home')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto-entreno/Salud/urls.py
from django.urls import path, include

from Salud import views

urls_aptos_fisicos = [
    path('list', views.LegajosTodosList.as_view(), name='list'),
    path('<pk>/update', views.AptoFisicoUpdate.as_view(), name='update'),
    path('<legajo>/create', views.AptoFisicoCreate.as_view(), name='create')
]

urls_legajos = [
    path('list', views.LegajosTodosList.as_view(), name='list'),
    path('<pk>/update', views.LegajoUpdate.as_view(), name='update'),
    path('<pk>/detail', views.LegajoSaludDetail.as_view(), name='detail')
]

urlpatterns = [
    path('legajos/', include((urls_legajos, 'Salud'), namespace='legajos')),
    path('aptos/fisicos/', include((urls_aptos_fisicos, 'Salud'), namespace='aptos_fisicos')),
]

proyecto-entreno/Salud/models.py
import logging

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.timezone import now

from Entreno.models import Atleta


class FactorRiesgo(models.Model):
    detalle = models.CharField(blank=False, null=False, max_length=256)

    class Meta:
        ordering = ["detalle"]
        verbose_name = "Factor de riesgo"
        verbose_name_plural = "Factores de riesgo"

    def __str__(self):
        return self.detalle


class LegajoSalud(models.Model):
    FACTOR_SANGUINEO_CHOICES = (
        (1, 'O+'),
        (2, 'A+'),
        (3, 'B+'),
        (4, 'AB+'),
        (5, 'O-'),
        (6, 'A-'),
        (7, 'B-'),
        (8, 'AB-'),
    )

    atleta = models.OneToOneField(Atleta, on_delete=models.CASCADE)
    deslinde = models.BooleanField(default=False)
    factor_sanguineo = models.IntegerField(
        choices=FACTOR_SANGUINEO_CHOICES,
        null=True, blank=True)
    factores_riesgo = models.ManyToManyField(FactorRiesgo, blank=True)

    def get_absolute_url(self):
        return reverse('Salud:legajos:detail', kwargs={'pk': self.id})

    class Meta:
        ordering = ["atleta__apellido", "atleta__nombre"]
        verbose_name = "Legajo de Salud"
        verbose_name_plural = "Legajos de salud"

    def tiene_certificado_vigente(self):
        return self.aptofisico_set.filter(fecha_vencimiento__gt=now()).exists()

    def __str__(self):
        return 'Leg. salud: ' + self.atleta.apellido + ', ' + self.atleta.nombre


class AptoFisico(models.Model):
    legajo = models.ForeignKey(LegajoSalud, on_delete=models.CASCADE)
    fecha_vencimiento = models.DateField()
    fecha_presentado = models.DateField(default=now)

    class Meta:
        verbose_name = "Apto Físico"
        verbose_name_plural = "Aptos Físicos"

    def __str__(self):
        return 'Apto fisico: ' + str(self.legajo) + ', f. vto.: ' + str(self.fecha_vencimiento)


@receiver(post_save, sender=Atleta)
def __crear_legajo_salud_on_atleta_post_save(sender, **kwargs):
    try:
        atleta = kwargs.get('instance')
        legajo, created = LegajoSalud.objects.get_or_create(atleta=atleta)
        logging.info(f'Legajo de salud: {legajo} Creado: {created}')
    except Exception as e:
        logging.exception(e)
        raise e

proyecto-entreno/Salud/forms.py
from django.forms import ModelForm, ModelMultipleChoiceField

from Salud.models import FactorRiesgo
from .models import LegajoSalud


class LegajoSaludModelForm(ModelForm):
    factores_riesgo = ModelMultipleChoiceField(queryset=FactorRiesgo.objects.all(), required=False)

    class Meta:
        model = LegajoSalud
        exclude = ['atleta']

proyecto-entreno/Salud/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import ListView, UpdateView, CreateView, DetailView

from PE.views import AjaxableResponseMixin, AjaxFormMixin
from Salud.forms import LegajoSaludModelForm
from Salud.models import LegajoSalud
from . import models


class LegajoSaludDetail(LoginRequiredMixin, DetailView):
    model = models.LegajoSalud
    template_name = 'legajosalud_detail.html'

    def get_context_data(self, **kwargs):
        context = super(LegajoSaludDetail, self).get_context_data(**kwargs)
        context['titulo'] = f"Legajo de salud"
        return context


class LegajosTodosList(LoginRequiredMixin, ListView):
    model = models.LegajoSalud
    template_name = 'legajosalud_list.html'


class LegajoUpdate(LoginRequiredMixin, AjaxableResponseMixin, AjaxFormMixin, UpdateView):
    model = models.LegajoSalud
    template_name = 'legajosalud_form.html'
    form_class = LegajoSaludModelForm

    def get_context_data(self, **kwargs):
        context = super(LegajoUpdate, self).get_context_data(**kwargs)
        legajo = context['object']  # type: LegajoSalud
        context['titulo'] = f"Legajo de salud: {legajo.atleta}"
        return context


class AptoFisicoTodosList(LoginRequiredMixin, ListView):
    model = models.AptoFisico
    template_name = 'aptofisico_list.html'


class AptoFisicoUpdate(LoginRequiredMixin, UpdateView):
    model = models.AptoFisico
    template_name = 'aptofisico_form.html'
    fields = ['fecha_presentado', 'fecha_vencimiento']

    def get_legajo(self):
        return self.object.legajo

    def get_context_data(self, **kwargs):
        context = super(AptoFisicoUpdate, self).get_context_data(**kwargs)
        apto = context['object']  # type: models.AptoFisico
        context['titulo'] = f"Actualizar apto físico N°{apto.id}: {apto.legajo.atleta}"
        return context


class AptoFisicoCreate(LoginRequiredMixin, CreateView):
    model = models.AptoFisico
    template_name = 'aptofisico_form.html'
    fields = ['fecha_presentado', 'fecha_vencimiento']

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.legajo = None

    def get_legajo(self):
        if self.legajo is None:
            self.legajo = LegajoSalud.objects.get(pk=self.kwargs['legajo'])
        return self.legajo

    def get_initial(self):
        initial = super().get_initial()
        initial['legajo'] = self.get_legajo()
        return initial

    def form_valid(self, form):
        apto = form.save(commit=False)  # type:models.AptoFisico
        apto.legajo = self.get_legajo()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(AptoFisicoCreate, self).get_context_data(**kwargs)
        context['titulo'] = f"Nuevo apto físico: {self.get_legajo().atleta}"
        return context

    def get_success_url(self):
        return self.get_legajo().get_absolute_url()

proyecto-entreno/Salud/templates/aptofisico_form.html
{% extends 'dashboard.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="box box-block bg-white">
        <h2 class="h-underline h-underline-100 h-underline-primary">{{ titulo }}
            <small class="text-muted"><a href="{% url 'Salud:legajos:detail' view.get_legajo.id %}"> ver </a></small>
        </h2>
        <div class="row">
            <div class="col-sm-12 col-md-3">
                {% with atleta=object.legajo.atleta %}
                    {% include 'perfil_atleta.html' %}
                {% endwith %}
            </div>
            <div class="col-sm-12 col-md-5">
                {% include 'form_generico.html' %}
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/bootstrap-datepicker/js/locales/bootstrap-datepicker.es.js' %}"></script>
    <script type="application/javascript">
        let datepicker_conf = {
            language: 'es',
            autoclose: true,
		    todayHighlight: true
        };
        $('#id_fecha_presentado').datepicker(datepicker_conf);
        $('#id_fecha_vencimiento').datepicker(datepicker_conf);
    </script>
{% endblock %}

proyecto-entreno/Salud/templates/aptofisico_list.html
{% extends 'datatable_shell.html' %}

{% block table_title %}
Todos los legajos
{% endblock %}

{% block thead %}
    <tr>
        <th>N° leg</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Deslinde</th>
        <th>Factor sanguíneo</th>
        <th>Factores riesgo</th>
    </tr>
{% endblock %}

{% block tbody %}
    {% for legajo in object_list %}
        <tr>
            <td><a href="{{ legajo.get_absolute_url }}">{{ legajo.id }}</a></td>
            <td>{{ legajo.atleta.nombre }}</td>
            <td>{{ legajo.atleta.apellido }}</td>
            <td>{{ legajo.deslinde | yesno }}</td>
            <td>{{ legajo.get_factor_sanguineo_display | default_if_none:'n/d' }}</td>
            <td>{{ legajo.factores_riesgo | default_if_none:'n/d' }}</td>
        </tr>
    {% endfor %}
{% endblock %}

{% block tfoot %}
    <tr>
        <th>N° leg</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Deslinde</th>
        <th>Factor sanguíneo</th>
        <th>Factores riesgo</th>
    </tr>
{% endblock %}

proyecto-entreno/Salud/templates/legajosalud_detail.html
{% extends 'datatable_shell.html' %}
{% load static %}

{% block content %}
    <div class="box box-block bg-white">
        <h2 class="h-underline h-underline-100 h-underline-primary">{{ titulo }}
            <small class="text-muted"><a href="{% url 'Salud:legajos:update' object.id %}"> editar </a></small>
        </h2>
        {% if subtitle %}
            <h6>{{ subtitle }}</h6>
        {% endif %}
        <div class="row">
            <div class="col-sm-12 col-md-3">
                {% with atleta=object.atleta %}
                    {% include 'perfil_atleta.html' %}
                {% endwith %}
            </div>
            <div class="col-sm-12 col-md-4">
                <div class="box box-block bg-white">
                    <h5>Detalles:</h5>
                    <div class="clearfix m-b-0-25">
                        <span class="pull-xs-left"><strong>Deslinde:</strong></span>
                        <span class="pull-xs-right">{{ object.deslinde | yesno | upper }}</span>
                    </div>
                    <div class="clearfix m-b-0-25">
                        <span class="pull-xs-left"><strong>Factor sanguíneo:</strong></span>
                        <span class="pull-xs-right">{{ object.get_factor_sanguineo_display }}</span>
                    </div>
                    <div class="clearfix m-b-0-25">
                        <span class="pull-xs-left"><strong>Factores riesgo:</strong></span>
                        <span class="pull-xs-right">
                        <ul>
                        {% for foo in object.factores_riesgo.all %}
                            <li>{{ foo }}</li>
                        {% endfor %}
                        </ul>
                    </span>
                    </div>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-sm-12">
                {{ block.super }} <!--Call to fucking table-->
            </div>
        </div>
    </div>
{% endblock %}

{% block table_title %}Aptos físicos
    <small class="text-muted"><a href="{% url 'Salud:aptos_fisicos:create' object.id %}"> nuevo </a>
    </small>{% endblock %}

{% block thead %}
    <tr>
        <th>ID</th>
        <th>Fecha vencimiento</th>
        <th>Fecha presentado</th>
    </tr>
{% endblock %}

{% block tbody %}
    {% for apto in object.aptofisico_set.all %}
        <tr>
            <td><a href="{% url 'Salud:aptos_fisicos:update' apto.id %}"
                   class="btn btn-outline-primary">{{ apto.id }}</a></td>
            <td>{{ apto.fecha_vencimiento }}</td>
            <td>{{ apto.fecha_presentado }}</td>
        </tr>
    {% endfor %}
{% endblock %}

proyecto-entreno/Salud/templates/legajosalud_form.html
{% extends 'dashboard.html' %}
{% load static %}

{% block content %}
    <div class="box box-block bg-white">
        <h2 class="h-underline h-underline-100 h-underline-primary">{{ titulo }}
            <small class="text-muted"><a href="{% url 'Salud:legajos:detail' object.id %}"> ver </a></small>
        </h2>
        <div class="row">
            <div class="col-sm-12 col-md-3">
                {% with atleta=object.atleta %}
                    {% include 'perfil_atleta.html' %}
                {% endwith %}
            </div>
            <div class="col-sm-12 col-md-5">
                {% include 'form_generico.html' %}
            </div>
        </div>
    </div>
{% endblock %}

proyecto-entreno/Salud/templates/legajosalud_list.html
{% extends 'datatable_shell.html' %}

{% block table_title %}
    Todos los legajos
{% endblock %}

{% block thead %}
    <tr>
        <th>N° leg</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Deslinde</th>
        <th>Apto físico vigente</th>
        <th>Factor sanguíneo</th>
        <th>Factores riesgo</th>
    </tr>
{% endblock %}

{% block tbody %}
    {% for legajo in object_list %}
        <tr>
            <td><a href="{{ legajo.get_absolute_url }}" class="btn btn-outline-primary">{{ legajo.id }}</a></td>
            <td>{{ legajo.atleta.nombre }}</td>
            <td>{{ legajo.atleta.apellido }}</td>
            <td>{{ legajo.deslinde | yesno }}</td>
            <td>{{ legajo.tiene_certificado_vigente | yesno }}</td>
            <td>{{ legajo.get_factor_sanguineo_display | default_if_none:'n/d' }}</td>
            <td>
                {% for foo in legajo.factores_riesgo.all %}
                    {{ foo }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </td>
        </tr>
    {% endfor %}
{% endblock %}

{% block tfoot %}
    <tr>
        <th>N° leg</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Deslinde</th>
        <th>Apto físico vigente</th>
        <th>Factor sanguíneo</th>
        <th>Factores riesgo</th>
    </tr>
{% endblock %}